{{- if not .Values.global.secretoExterno }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "db-credenciales") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "db") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.global.dbName | quote }}
  POSTGRES_USER: {{ .Values.global.dbUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.dbPassword | quote }}
{{- end }}
