apiVersion: v2
name: sa-platform
description: Plataforma de tickets de soporte - Practica 5 Software Avanzado (orquestacion con Helm)
type: application
version: 1.1.0
appVersion: "1.0.0"

dependencies:
  - name: db
    version: "1.0.0"
  - name: broker
    version: "1.0.0"
  - name: auth-service
    version: "1.0.0"
  - name: tickets-service
    version: "1.0.0"
  - name: comentarios-service
    version: "1.0.0"
  - name: notificaciones-service
    version: "1.0.0"
  - name: api-gateway
    version: "1.0.0"
  - name: postgresql
    version: "15.5.20"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "14.6.6"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: rabbitmq.enabled
