apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "notificaciones-service-config") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "notificaciones-service") | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}
  COLA_TICKETS_RESUELTOS: {{ .Values.global.rabbitmqQueueTicketsResueltos | default "tickets.resueltos" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "notificaciones-service-secret") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "notificaciones-service") | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ printf "amqp://%s:%s@%s:5672/%%2F" .Values.global.rabbitmqUsername .Values.global.rabbitmqPassword (include "sa-platform.fullname" (dict "root" $ "name" "broker")) | quote }}
