replicaCount: 4

image:
  repository: ghcr.io/susanpamela2520/pr-cticas-sa-b-201612218/api-gateway
  tag: v1.1.9
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

rollout:
  enabled: true
  progressDeadlineSeconds: 300
  steps:
    - { peso: 20, pausa: 2m }
    - { peso: 50, pausa: 2m }
    - { peso: 100, pausa: 1m }

analisis:
  intervalo: 30s
  repeticiones: 4
  exitoMinimo: 99
  latenciaMaximaMs: 500

probes:
  readiness:
    periodSeconds: 5
    failureThreshold: 3
  liveness:
    periodSeconds: 10
    failureThreshold: 3

podDisruptionBudget:
  enabled: true
  minAvailable: 2

antiAfinidad:
  enabled: true
