apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "api-gateway-config") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "api-gateway") | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}
  AUTH_SERVICE_URL: {{ printf "http://%s:3001" (include "sa-platform.fullname" (dict "root" $ "name" "auth-service")) | quote }}
  TICKETS_SERVICE_URL: {{ printf "http://%s:8001" (include "sa-platform.fullname" (dict "root" $ "name" "tickets-service")) | quote }}
  COMENTARIOS_SERVICE_URL: {{ printf "http://%s:3002" (include "sa-platform.fullname" (dict "root" $ "name" "comentarios-service")) | quote }}
  NOTIFICACIONES_SERVICE_URL: {{ printf "http://%s:8002" (include "sa-platform.fullname" (dict "root" $ "name" "notificaciones-service")) | quote }}
