apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "broker") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "broker") | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "broker") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
  apiGroup: rbac.authorization.k8s.io
