{{- if not .Values.global.secretoExterno }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker-credenciales") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "broker") | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.global.rabbitmqUsername | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.global.rabbitmqPassword | quote }}
{{- end }}
