apiVersion: v1
kind: Service
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "broker") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "broker") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
