apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/susanpamela2520/Pr-cticas-SA-B-201612218-gitops.git
    targetRevision: main
    path: charts/sa-platform
    helm:
      releaseName: sa-platform
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/selector
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 10
