apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "auth-service-config") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "auth-service") | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}
  DB_HOST: {{ include "sa-platform.fullname" (dict "root" $ "name" "db") | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.global.dbName | quote }}
  JWT_TTL_SEGUNDOS: {{ .Values.global.jwtTtlSegundos | default 900 | quote }}
  JWT_RENOVACION_GRACIA_SEGUNDOS: {{ .Values.global.jwtRenovacionGraciaSegundos | default 300 | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | default "info" | quote }}
  COOKIE_SECURE: "false"
{{- if not .Values.global.secretoExterno }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-platform.fullname" (dict "root" $ "name" "auth-service-secret") }}
  labels:
    {{- include "sa-platform.labels" (dict "root" $ "componente" "auth-service") | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.global.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.global.dbPassword | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  AES_KEY_HEX: {{ .Values.global.aesKeyHex | quote }}
  CORREO_HASH_SECRET: {{ .Values.global.correoHashSecret | quote }}
{{- end }}
